### PR TITLE
HDF5 support for wavefunction and overall generalization

### PR DESCRIPTION
**Pull request by S-Erik**
Main changes are:
- Adding a `save_wfc` flag to the input file by adding a bool value to *control/lib.rs*
- Main hdf5 saving and loading is now implemented in *dfttypes/lib.rs* as functions on `VKEigenVector` and `RHOR`. Saving and loading specific matrix and array object is implemented in their respective files, i.e. in *matrix/matrix_c64.rs*, *matrix/matrix_f64.rs*, *lattice/lib.rs*, *ndarray/array3_c64.rs* and *pwbasis/lib.rs*
- Besides the wavefunction and density coefficients, we now save additional information about the plane-wave basis and the reciprocal lattice. Each information piece is saved and loaded in and from a hdf5 group with the name of the information piece, e.g. we save a hdf5 group named PWBasis for the `PWBasis` object.

Aspects of further implementation:
- Although a `load_hdf5` function is implemented for `RHOR` in *dfttypes/lib.rs*, it is currently only able to load spin-unpolarized densities. For spin-polarized densities we need to load from two files because we currently save the spin-up and spin-down densities to different files in the `save_hdf5` function. This means that the function signature of `load_hdf5` needs to be different for spin-unpolarized and spin-polarized densities because we need to load from one or two files, respectively. Possible solutions are: saving spin-polarized densities into only one file instead of two files. Or, defining a type that handles the one or two filenames. The latter could be implemented as follows:
```rust
pub enum FilenameTypes<'a> {
    NonSpin(&'a str),
    Spin(&'a str, &'a str),
}

pub fn load_hdf5(&mut self, filename: FilenameTypes) {
```
- The rust hdf5 crate natively supports complex values on the development GitHub branch. When this gets released, the `save_hdf5` and `load_hdf5` in *matrix/matrix_c64.rs* and *matrix/matrix_f64.rs* can be moved to *matrix/lib.rs*.

**I think the changes presented here need to be carefully reviewed such that they align with what the direction of dftworks is concerning the HDF5 support.**

# Related issues
#6

### CODE REVIEW

**Comment by dftworks** [comment]
Since we use fixed filenames for the computed density — out.scf.rho.hdf5 for the non-spin case and out.scf.rho.up.hdf5 and out.scf.rho.dn.hdf5 for the spin case — there is no need to provide filenames for the load_hdf5 function. The code can be as shown below:

```
pub fn load_hdf5(&mut self) {
...
}
```

**Comment by dftworks** [comment]
The [gindex in PWBasis](https://github.com/dftworks/dftworks/blob/9e3430cc20a423b76120fae17fab16aaefac61d1/pwbasis/src/lib.rs#L10) stores the indices of G vectors used in this set of plane wave basis. For restarting and post-processing purposes, gindex needs to be saved.

**Review by dftworks — APPROVED** [review]
Great and thanks a lot!

**Comment by S-Erik** [comment]
For the following suggestions you made I will prepare a new PR since this one is closed now:
- Removing the `filename` argument from the `RHOR::load_hdf5` function
- The `gindex` in `PWBasis` is not saved to the hdf5 file

**Pull request merged**
